name: Build for Linux
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install deps
        run: sudo apt install xorg-dev libgl-dev

      - name: Build
        run: make

      - name: Upload zip
        uses: actions/upload-artifact@v2
        with:
          name: piral-linux.zip
          path: piral-out
